#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/../.."

FRONTEND_VERSION="20240528140736"

rm -rf ./custom_components/hacs/hacs_frontend
scripts/install/pip_packages --target=./custom_components/hacs "hacs_frontend==${FRONTEND_VERSION}"
rm -rf ./custom_components/hacs/*.dist-info
