#!/usr/bin/env bash

set -e

if command -v uv >/dev/null 2>&1; then
    exec uv pip install \
        --constraint constraints.txt \
        "${@}"
fi

python3 -m pip \
    install \
    --upgrade \
    --disable-pip-version-check \
    --constraint constraints.txt \
    "${@}"

