extends: airbnb-base
parser: "@typescript-eslint/parser"
rules:
  no-else-return: 0
  no-underscore-dangle: 0
  nonblock-statement-body-position: 0
  curly: 0
  no-console: 2
  no-return-assign: 0
  consistent-return: 0
  no-mixed-operators: 0
  class-methods-use-this: 0
  no-nested-ternary: 0
  camelcase: 0
  no-unused-vars: 0
  quotes: 0
  comma-dangle: 0
  import/no-unresolved: 0
  import/prefer-default-export: 0
globals:
  window: true
  Event: true
  customElements: true