---
name: "Frontend"
description: You use this when elements in the UI are not working correctly.
labels: "issue:frontend"
body:
- type: markdown
  attributes:
    value: |
      Learn how to submit an issue here https://hacs.xyz/docs/help/issues/
      Before you open a new issue, search through the existing issues to see if others have had the same problem.

      The issue template is not a suggestion, fill out everything that is asked.
- type: markdown
  attributes:
    value: "## Installation details"
- type: input
  attributes:
    label: Web browser
    description: The type of browser you are using
  validations:
    required: true
- type: input
  attributes:
    label: Web browser version
    description: The version of the browser you are using
  validations:
    required: true
- type: textarea
  attributes:
    label: "System Health details"
    description: "Paste the data from the System Health card in Home Assistant (https://www.home-assistant.io//more-info/system-health#github-issues)"
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
        required: true
      - label: I have filled out the issue template to the best of my ability.
        required: true
      - label: I have read <https://hacs.xyz/docs/help/issues/>
        required: true
      - label:  This issue is related to the frontend of HACS.
        required: true
      - label: This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
        required: true
      - label: This is a bug and not a feature request.
        required: true
      - label: This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).
        required: true
- type: textarea
  attributes:
    label: Describe the issue
    placeholder: "A clear and concise description of what the issue is."
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: "Without steps to reproduce, it will be hard to fix, it is very important that you fill out this part, issues without it will be closed"
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    placeholder: "Here you paste screenshots to showcase the issue."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Javascript logs from your browser console"
    render: text
  validations:
    required: true
- type: textarea
  attributes:
    label: "Debug logs"
    description: "To enable debug logs check this https://hacs.xyz/docs/use/troubleshooting/logs/, this **needs** to include _everything_ from startup of Home Assistant to the point where you encounter the issue."
    render: text
  validations:
    required: true
- type: textarea
  attributes:
    label: "Diagnostics dump"
    description: "Drag or paste the diagnostics dump file here. (see https://hacs.xyz/docs/use/troubleshooting/diagnostics/ for info)"
  validations:
    required: true
