---
name: "HACS Add-ons"
description: You use this when there is an issue with one of the HACS Add-ons
labels: "issue:addon"
body:
- type: markdown
  attributes:
    value: |
      Learn how to submit an issue here https://hacs.xyz/docs/help/issues/
      Before you open a new issue, search through the existing issues to see if others have had the same problem.

      The issue template is not a suggestion, fill out everything that is asked.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have filled out the issue template to the best of my ability.
        required: true
      - label: I have read <https://hacs.xyz/docs/help/issues/>
        required: true
      - label:  This issue is related to one the HACS add-ons.
        required: true
      - label: This is a bug and not a feature request.
        required: true
      - label: This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
        required: true
- type: dropdown
  validations:
    required: true
  attributes:
    label: Which Add-on are you reporting an issue for?
    options:
      - get
- type: textarea
  attributes:
    label: Describe the issue
    placeholder: "A clear and concise description of what the issue is."
  validations:
    required: true

- type: textarea
  attributes:
    label: Add-on logs
  validations:
    required: true

- type: textarea
  attributes:
    label: Supervisor logs
  validations:
    required: true

- type: textarea
  attributes:
    label: "Diagnostics dump"
    description: "Drag or paste the diagnostics dump file here. (see https://hacs.xyz/docs/use/troubleshooting/diagnostics/ for info)"
  validations:
    required: true
