#!/usr/bin/env bash

function StartHomeAssistant {
  echo "Copy configuration.yaml"
  cp -f .devcontainer/configuration.yaml /config || echo ".devcontainer/configuration.yaml are missing!" exit 1

  echo "Copy the custom component"
  rm -R /config/custom_components/ || echo ""
  cp -r custom_components /config/custom_components/ || echo "Could not copy the custom_component" exit 1

  echo "Start Home Assistant"
  hass -c /config
}

function UpdgradeHomeAssistantDev {
  python -m pip install --upgrade git+git://github.com/home-assistant/home-assistant.git@dev
}

function SetHomeAssistantVersion {
  read -p 'Version: ' version
  python -m pip install --upgrade homeassistant==$version
}

function HomeAssistantConfigCheck {
  hass -c /config --script check_config
}

function InstallTabNine {
  echo "Enable TabNine autocomplete"
  mkdir -p /root/.config/TabNine
  cp -f .devcontainer/tabnine_config.json /root/.config/TabNine
  while [ -z "$CLOUD_KEY" ]; do
    echo "Enter cloudkey:"
    read CLOUD_KEY
  done
  sed -i "s/REPLACE_CLOUD_KEY/$CLOUD_KEY/g" /root/.config/TabNine/tabnine_config.json
  echo "TabNine autocomplete done!"
}