#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

scripts/install/pip_packages "pip<23.2,>=21.3.1"
scripts/install/pip_packages setuptools wheel
scripts/install/pip_packages --requirement requirements_lint.txt
scripts/install/pip_packages --requirement requirements_core_min.txt
scripts/install/pip_packages --requirement requirements_test.txt
scripts/install/frontend
