on: 
  push: 
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
      runs-on: "ubuntu-latest"
      steps: 
          - uses: actions/checkout@v4
          - uses: home-assistant/actions/hassfest@master
  test: 
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4