name: Publish

on:
  release:
    types:
      - published
  push:
    branches:
      - main

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  release_zip_file:
    name: Publish HACS zip file asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 🛠️ Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: 🔢 Get version
        if: ${{ github.event_name == 'release' }}
        id: version
        uses: home-assistant/actions/helpers/version@e91ad1948e57189485b9c1ad608af0c303946f89 # master

      - name: 🔢 Set version number
        if: ${{ github.event_name == 'release' }}
        run: |
          sed -i "/MINIMUM_HA_VERSION = /c\MINIMUM_HA_VERSION = \"$(jq .homeassistant -r ${{ github.workspace }}/hacs.json)\"" ${{ github.workspace }}/custom_components/hacs/const.py
          python3 ${{ github.workspace }}/scripts/update/manifest.py --version ${{ steps.version.outputs.version }}

      - name: ⏬ Download HACS frontend
        run: ${{ github.workspace }}/scripts/install/frontend

      - name: 📤 Upload zip to action
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ github.event_name == 'push' }}
        with:
          name: hacs
          path: ${{ github.workspace }}/custom_components/hacs
          retention-days: 7

      # Pack the HACS dir as a zip and upload to the release
      - name: 📦 ZIP HACS Dir
        if: ${{ github.event_name == 'release' }}
        run: |
          cd ${{ github.workspace }}/custom_components/hacs
          zip hacs.zip -r ./

      - name: 📤 Upload zip to release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        if: ${{ github.event_name == 'release' }}
        with:
          files: ${{ github.workspace }}/custom_components/hacs/hacs.zip

