name: 'Close stale issues'

on:
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * *'

permissions: {}

jobs:
  issues_missing_required_information:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899  # v10.3.0
        with:
          days-before-stale: -1
          days-before-close: 7
          only-labels: 'Missing required issue information'
          stale-issue-label: 'Missing required issue information'
