#!/usr/bin/env bash

set -e

FRONTEND_VERSION="20220707075909"

python3 -m pip --disable-pip-version-check install -U --target=./custom_components/hacs "hacs_frontend==$FRONTEND_VERSION"
rm -rf ./custom_components/hacs/*.dist-info