#!/usr/bin/env bash

set -e

FRONTEND_VERSION="20211231144850"

python3 -m pip install -U --target=./custom_components/hacs "hacs_frontend==$FRONTEND_VERSION"
rm -rf ./custom_components/hacs/*.dist-info